---
- name: Fail if mandatory parameters are not set
  ansible.builtin.fail:
    msg: "Mandatory parameter '{{ item.name }}' must be set and not left as 'MANDATORY_PARAMETER_PLACEHOLDER'."
  when: item.value is not defined or item.value == 'MANDATORY_PARAMETER_PLACEHOLDER'
  loop:
    - { name: "ionos_config.data_center_uuid", value: "{{ ionos_config.data_center_uuid | default(omit) }}" }
    - { name: "ionosctl.token", value: "{{ ionosctl.token | default(omit) }}" }

- name: Include get-uuids.yml tasks if enabled
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/get-uuids.yaml"
  when: get_dc_uuids | bool

- name: Include render-driver-hooks.yaml tasks if enabled
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/render-driver-hooks.yaml"
  when: render_driver_hooks | bool
  
- name: Include distribute-uuids.yaml tasks if enabled
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/tasks/distribute-uuids.yaml"
  when: distribute_uuids | bool
  