---
ansible_python_interpreter: /usr/bin/python3

validation:
  create_vnet: false
  conn_matrix:
    bridge_name: br1
    vnet_name: vxlan
  vm:
    check_connection: true
    market_name: 'Alpine Linux 3.20'
  vnet:
    name: 'pubridge'
  run_storage_benchmark: true
  storage_benchmark:
    vnet_name: 'pubridge'
